"""empty message

Revision ID: c91475c65ec2
Revises: 
Create Date: 2018-12-21 10:55:44.171688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91475c65ec2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_courses',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('study_groups',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department_title', sa.String(length=128), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('course_x_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['study_courses._id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups._id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('study_group_id', sa.Integer(), nullable=True),
    sa.Column('degree', sa.String(length=128), nullable=True),
    sa.Column('form_of_study', sa.String(length=128), nullable=True),
    sa.Column('learning_base', sa.String(length=128), nullable=True),
    sa.Column('type_of_user', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('teacher_x_course',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['study_courses._id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_x_course')
    op.drop_table('users')
    op.drop_table('course_x_group')
    op.drop_table('study_groups')
    op.drop_table('study_courses')
    # ### end Alembic commands ###
